### PR TITLE
Fixes Issue #1868 - Renaming project to same title as previous still shows publish changes prompt

### LINKED ISSUE #1868: Renaming project to same title as previous still shows publish changes prompt
If you click 'Save' on the project title without renaming, the update published project button still shows.

I've fixed this locally and will create a new PR.

### PR DESCRIPTION
**Pull request by lkisac**
Fixes #1868 

Continuation of #719

### CODE REVIEW

**Comment by lkisac** [comment]
I just realized [this](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/editor/js/fc/project-rename.js#L121) line should be comparing with the published project metadata, not just project's current title.  I will update PR once I've completed.

**Comment by lkisac** [comment]
@gideonthomas @humphd  I used the same code in [here](https://github.com/mozilla/thimble.mozilla.org/blob/master/public/editor/scripts/project/project.js#L148-L175) and slightly modified it for [project-rename.js](https://gist.github.com/lkisac/e7f877aba3135b4a33b22d8dc55a9649) `save` function.  It's still not comparing against the actual published title.  

It works when I leave the title unchanged and click 'Save', but if I rename it and save, then rename it back to the published title again it will still show the 'Update published version' button.

image

Since this is related to Issue [#240](https://github.com/mozilla/publish.webmaker.org/issues/240), should I wait until that one is resolved before starting on this one?

I'm interested to know your feedback and if there's any specific way you would want this implemented as well.

**Comment by flukeout** [comment]
Hey @lkisac - thank you for the PR - I think in the case when someone renames, and then re-renames back to the original name, it's okay to show the Update Published version - I think it's a rare case. I guess mostly what we want to prevent is when someone doesn't really want to rename it and hit saves to preserve the original name.

Is this ready to test?

**Comment by lkisac** [comment]
@flukeout  Thanks for your input.  

_"When someone renames, and then re-renames back to the original name, it's okay to show the Update Published version"_   

If this is ok, PR is ready to test.

**Comment by flukeout** [comment]
Sounds good - testing now

File: public/editor/scripts/editor/js/fc/project-rename.js [hunk 1]
```diff
@@ -117,28 +117,31 @@ define(function(require) {
...
+      editingComplete(context);
+    }
+    else {
+      context.saveButton.text("{{ renameProjectSavingIndicator }}");
 
-      Project.setTitle(context.titleBar.val(), function(err) {
-        if (err) {
-          console.error("[Bramble] Failed to update the project internally: ", err);
+      persist.call(context, context.titleBar.val(), function(err) {
+        if(err) {
```
Comment (flukeout) [inline public/editor/scripts/editor/js/fc/project-rename.js]: Change to ``if (err) {`` - add space between if and ()

File: public/editor/scripts/editor/js/fc/project-rename.js [hunk 2]
```diff
@@ -117,28 +117,31 @@ define(function(require) {
...
-    persist.call(context, context.titleBar.val(), function(err) {
-      if(err) {
-        console.error("[Bramble] Failed to rename the project with ", err);
-        return;
-      }
+    // Do not apply save if project title remains the same
+    if (context.titleBar.val() == Project.getTitle()) {
+      editingComplete(context);
+    }
+    else {
```
Comment (flukeout) [inline public/editor/scripts/editor/js/fc/project-rename.js]: Move else to previous line so it is ``} else {``

File: public/editor/scripts/editor/js/fc/project-rename.js [hunk 3]
```diff
@@ -117,28 +117,31 @@ define(function(require) {
...
+      context.saveButton.text("{{ renameProjectSavingIndicator }}");
 
-      Project.setTitle(context.titleBar.val(), function(err) {
-        if (err) {
-          console.error("[Bramble] Failed to update the project internally: ", err);
+      persist.call(context, context.titleBar.val(), function(err) {
+        if(err) {
+          console.error("[Bramble] Failed to rename the project with ", err);
```
Comment (flukeout) [inline public/editor/scripts/editor/js/fc/project-rename.js]: Change to ``console.error("[Bramble] Failed to rename the project. Error:  ", err);``

**Comment by flukeout** [comment]
Ok great, just tested this and it works as expected. Please fix up the few minor nitpicks that I've left. @Pomax can you have a quick look over the code as well?

File: public/editor/scripts/editor/js/fc/project-rename.js [hunk 4]
```diff
@@ -117,28 +117,31 @@ define(function(require) {
...
   function save(context) {
-    context.saveButton.text("{{ renameProjectSavingIndicator }}");
-
-    persist.call(context, context.titleBar.val(), function(err) {
-      if(err) {
-        console.error("[Bramble] Failed to rename the project with ", err);
-        return;
-      }
+    // Do not apply save if project title remains the same
+    if (context.titleBar.val() == Project.getTitle()) {
```
Comment (flukeout) [inline public/editor/scripts/editor/js/fc/project-rename.js]: Use ``===`` for the comparison.

File: public/editor/scripts/editor/js/fc/project-rename.js [hunk 5]
```diff
@@ -117,28 +117,30 @@ define(function(require) {
...
-    persist.call(context, context.titleBar.val(), function(err) {
-      if(err) {
-        console.error("[Bramble] Failed to rename the project with ", err);
-        return;
-      }
+    // Do not apply save if project title remains the same
+    if (context.titleBar.val() === Project.getTitle()) {
+      editingComplete(context);
+    } else {
+      context.saveButton.text("{{ renameProjectSavingIndicator }}");
```
Comment (Pomax) [inline public/editor/scripts/editor/js/fc/project-rename.js]: does this template string actually get replaced? I don't remember how or why this worked.. (if you don't know that's fine, just trying to remember what magic happened here)

File: public/editor/scripts/editor/js/fc/project-rename.js [hunk 6]
```diff
@@ -117,28 +117,30 @@ define(function(require) {
...
   function save(context) {
-    context.saveButton.text("{{ renameProjectSavingIndicator }}");
-
-    persist.call(context, context.titleBar.val(), function(err) {
-      if(err) {
-        console.error("[Bramble] Failed to rename the project with ", err);
-        return;
-      }
+    // Do not apply save if project title remains the same
+    if (context.titleBar.val() === Project.getTitle()) {
```
Comment (Pomax) [inline public/editor/scripts/editor/js/fc/project-rename.js]: we can lift this out as a variable `var contextTitle = context.titleBar.val();` and then we can use that `contextTitle` here, as well as on line 126 and 132

**Comment by Pomax** [comment]
few small things but overall this looks pretty good!

File: public/editor/scripts/editor/js/fc/project-rename.js (hunk 5 above)
Comment (lkisac) [inline public/editor/scripts/editor/js/fc/project-rename.js]: Thanks for the feedback @Pomax!  

I've made the changes in recent commit.  Regarding the template string, all I know is that they get replaced by the values defined in messages.json

**Comment by flukeout** [comment]
Hey @Pomax - can we merge this now? I tested again with latest changes and it works.

File: public/editor/scripts/editor/js/fc/project-rename.js [hunk 7]
```diff
@@ -117,28 +117,31 @@ define(function(require) {
...
           return;
         }
-        editingComplete(context);
-        analytics.event("ProjectRenamed");
 
-        //  Check whether the project is not anonymous		
-        if(context.publisher){
-          context.publisher.showUnpublishedChangesPrompt();		
-        }
+        Project.setTitle(context.titleBar.val(), function(err) {
```
Comment (Pomax) [inline public/editor/scripts/editor/js/fc/project-rename.js]: we extracted this as `contextTitle` so just use that instead of calling `context.titleBar.val()` a second time.

**Comment by Pomax** [comment]
@flukeout @lkisac one thing and once that's addressed this is good to land.

**Comment by Pomax** [comment]
this looks good to me - if you're happy with this too @flukeout you can hit the "approve changes" link next to your review and then merge away!
